apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: aiops-triage
    app.kubernetes.io/part-of: dashtab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aiops-triage
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
