{{- if .Values.alertmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dashtab-alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: dashtab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: http
{{- end }}
